// MATRIYA Control Room — a READ-ONLY tab. It only displays studioData(): no
// approvals, no writes, no ledger changes. It fetches a snapshot, auto-refreshes
// on an interval, and shows a SAMPLE / LIVE / PENDING badge. Nothing here mutates
// anything — by design, until two days of use tell us which buttons are safe.
import React, { useState, useEffect, useCallback } from 'react';
import './ControlRoomTab.css';

// Source of the data: a live read-only endpoint if configured, else the static
// snapshot shipped in public/ (regenerated by `matriya studio`). Read-only either way.
const SRC = process.env.REACT_APP_CONTROL_ROOM_URL || '/control-room.json';
const REFRESH_MS = 15000;

const dot = (s) => ({ online: '#39d98a', offline: '#ff5470', standby: '#6b7280', green: '#39d98a', amber: '#ffb454', red: '#ff5470' }[s] || '#6b7280');
const chip = (c) => ({ NEW: '#39d98a', UPDATED: '#54a0ff', DELETED: '#ff5470' }[c] || '#6b7280');
const tagColor = (t) => ({ adhesion: '#54a0ff', strength: '#ffb454', color: '#c56cf0', fire: '#ff5470', flow: '#39d98a', process: '#48dbfb', note: '#6b7280' }[t] || '#6b7280');
const LL = { idle: ['#6b7280', 'IDLE'], evidence: ['#39d98a', 'EVIDENCE IN'], event: ['#ffb454', 'KNOWLEDGE EVENT'], discovery: ['#c56cf0', 'DISCOVERY'], boundary: ['#ff9f43', 'BOUNDARY'], refutation: ['#ff5470', 'REFUTATION'] };
const pctOf = (v, max) => Math.max(4, Math.round((v / Math.max(1, max)) * 100));

function Meter({ label, val, max, color }) {
  return (
    <div className="cr-meter">
      <div className="cr-meter-row"><span>{label}</span><b>{val}</b></div>
      <div className="cr-bar"><i style={{ width: pctOf(val, max) + '%', background: color }} /></div>
    </div>
  );
}

export default function ControlRoomTab() {
  const [data, setData] = useState(null);
  const [status, setStatus] = useState('PENDING'); // PENDING | OK | ERROR
  const [updated, setUpdated] = useState(null);

  const load = useCallback(async () => {
    try {
      const r = await fetch(SRC, { cache: 'no-store' });
      if (!r.ok) throw new Error(String(r.status));
      const j = await r.json();
      setData(j);
      setStatus('OK');
      setUpdated(new Date());
    } catch (e) {
      // keep showing the last good data if we have it; only show ERROR if we never loaded
      setStatus((prev) => (prev === 'OK' ? 'OK' : 'ERROR'));
    }
  }, []);

  useEffect(() => {
    load();
    const t = setInterval(load, REFRESH_MS);
    return () => clearInterval(t);
  }, [load]);

  if (!data) {
    return (
      <div className="control-room">
        <div className="cr-empty">
          {status === 'ERROR'
            ? <>Control Room data not reachable. It is read-only — generate it with <code>matriya studio</code> (writes <code>public/control-room.json</code>) or run <code>node studio/studio-server.mjs</code> and set <code>REACT_APP_CONTROL_ROOM_URL</code>.</>
            : 'Loading the Control Room…'}
        </div>
      </div>
    );
  }

  const badge = status === 'ERROR' ? 'PENDING' : (data.mode || 'SAMPLE');
  const [llColor, llText] = LL[data.learningLight?.state] || LL.idle;
  const rp = data.researchPhase || {};
  const maxPhase = Math.max(rp.discovery || 0, rp.validation || 0, rp.production || 0, 1);
  const cf = data.changeFeed || {};
  const cfMax = Math.max(cf.changesToday || 0, 6);
  const q = data.qualification || {};
  const g = data.knowledgeGrowth || {};
  const v = data.validation || {};

  return (
    <div className="control-room">
      <div className="cr-head">
        <div className="cr-brand">MATRIYA<small>RESEARCH STUDIO · CONTROL ROOM</small></div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span className={`cr-badge ${badge}`}>{badge}</span>
          <div className="cr-led" title={data.learningLight?.states?.[data.learningLight?.state] || ''}>
            <span className="lamp" style={{ background: llColor, boxShadow: `0 0 18px ${llColor},0 0 4px ${llColor}` }} />
            <div><b>{llText}</b><small>LEARNING</small></div>
          </div>
        </div>
      </div>

      <div className="cr-meta">
        <span>read-only · auto-refresh {REFRESH_MS / 1000}s</span>
        {updated && <span>· updated {updated.toLocaleTimeString()}</span>}
        <span>· this view never approves or writes</span>
      </div>

      <div className="cr-health">
        {(data.systemHealth || []).map((s) => (
          <div className="cr-src" key={s.source} title={s.note}>
            <i style={{ background: dot(s.state) }} />{s.source} <span style={{ color: '#8b98a9' }}>· {s.state}</span>
          </div>
        ))}
      </div>

      <div className="cr-episodes">
        <span className="cr-es-label">EPISODES BY ASSET</span>
        {(data.episodesByAsset || []).map((e) => (
          <span className="cr-es-chip" key={e.asset}><b>{e.episodes}</b> {e.asset.split(' ')[0]}</span>
        ))}
        {data.pendingEpisodes ? <span className="cr-es-chip pending"><b>{data.pendingEpisodes}</b> Fire · pending</span> : null}
        <span className="cr-es-note">— not "documents": units of knowledge you can compare, search, connect</span>
      </div>

      <div className="cr-grid">
        {/* CH1 — Incoming Signals */}
        <div className="cr-ch"><div className="num">CH1</div><h3>Incoming Signals <span>· sources</span></h3>
          {(data.incoming || []).length ? data.incoming.map((grp) => (
            <div className="cr-row" key={grp.source}>
              <span style={{ color: '#8b98a9' }}>{grp.source}</span>
              <span>{grp.items.map((it, i) => (
                <b key={i} style={{ color: chip(it.change) }}>{it.name.split('.')[0].slice(0, 14)}{i < grp.items.length - 1 ? ', ' : ''}</b>
              ))}</span>
            </div>
          )) : <div className="cr-row">quiet</div>}
        </div>

        {/* CH2 — Change Feed */}
        <div className="cr-ch"><div className="num">CH2</div><h3>Change Feed <span>· peak</span></h3>
          <Meter label="changes today" val={cf.changesToday || 0} max={cfMax} color="#48dbfb" />
          <Meter label="waiting review" val={cf.waiting || 0} max={cfMax} color="#ffb454" />
          <Meter label="approved" val={cf.approved || 0} max={cfMax} color="#39d98a" />
          <div className="cr-tag">NEW {cf.breakdown?.NEW || 0} · UPD {cf.breakdown?.UPDATED || 0} · DEL {cf.breakdown?.DELETED || 0} · {cf.source}</div>
        </div>

        {/* CH3 — Qualification */}
        <div className="cr-ch"><div className="num">CH3</div><h3>Qualification <span>· compressor</span></h3>
          <div className="cr-lights">
            <div className="cr-light"><i style={{ color: dot(q.units) }} />Units <span style={{ color: '#8b98a9' }}>— intelligible?</span></div>
            <div className="cr-light"><i style={{ color: dot(q.baseline) }} />Baseline <span style={{ color: '#8b98a9' }}>— vs corpus?</span></div>
            <div className="cr-light"><i style={{ color: dot(q.physics) }} />Physics <span style={{ color: '#8b98a9' }}>— possible?</span></div>
            <div className="cr-light"><i style={{ color: dot(q.review) }} />Review <span style={{ color: '#8b98a9' }}>— to human</span></div>
          </div>
          <div className="cr-tag">gate {q.gate?.passed}/{q.gate?.total} · red ⇒ it does not pass</div>
        </div>

        {/* CH4 — Human Review */}
        <div className="cr-ch"><div className="num">CH4</div><h3>Human Review <span>· control</span></h3>
          <div className="cr-kpi" style={{ marginBottom: 8 }}><b>{data.humanReview?.waiting || 0}</b><span>WAITING FOR A HUMAN</span></div>
          {(data.humanReview?.lanes || []).map((l) => (
            <div className="cr-row" key={l.lane}><span style={{ color: '#8b98a9' }}>{l.lane}</span><b>{l.count}</b></div>
          ))}
        </div>

        {/* CH5 — Knowledge Growth */}
        <div className="cr-ch"><div className="num">CH5</div><h3>Knowledge Growth <span>· today</span></h3>
          <div className="cr-grow">
            <div className="cr-kpi"><b style={{ color: '#39d98a' }}>+{g.confirmations || 0}</b><span>CONFIRMATIONS</span></div>
            <div className="cr-kpi"><b style={{ color: '#c56cf0' }}>+{g.discoveries || 0}</b><span>DISCOVERIES</span></div>
            <div className="cr-kpi"><b style={{ color: '#ff9f43' }}>+{g.boundaries || 0}</b><span>BOUNDARIES</span></div>
            <div className="cr-kpi"><b style={{ color: '#ff5470' }}>{g.refutations || 0}</b><span>REFUTATIONS</span></div>
          </div>
        </div>

        {/* CH6 — Evolution */}
        <div className="cr-ch" style={{ gridColumn: 'span 2' }}><div className="num">CH6</div><h3>Evolution <span>· {data.evolution?.product}</span></h3>
          <div className="cr-tl">
            {(data.evolution?.events || []).map((e) => (
              <div className="cr-pt" key={e.id} title={e.label}><i style={{ color: tagColor(e.tag) }} /><span>{e.tag}</span></div>
            ))}
          </div>
        </div>

        {/* CH7 — Research Phase */}
        <div className="cr-ch"><div className="num">CH7</div><h3>Research Phase <span>· VU</span></h3>
          <div className="cr-vu">
            <div className="cr-vbar"><div className="f" style={{ height: pctOf(rp.discovery || 0, maxPhase) + '%', background: '#39d98a' }} /><span>Disc</span><b>{rp.discovery || 0}</b></div>
            <div className="cr-vbar"><div className="f" style={{ height: pctOf(rp.validation || 0, maxPhase) + '%', background: '#ffb454' }} /><span>Valid</span><b>{rp.validation || 0}</b></div>
            <div className="cr-vbar"><div className="f" style={{ height: pctOf(rp.production || 0, maxPhase) + '%', background: '#ff5470' }} /><span>Prod</span><b>{rp.production || 0}</b></div>
          </div>
          <div className="cr-tag">phase {rp.phase} · index {rp.phaseIndex}</div>
        </div>

        {/* CH8 — Knowledge Entropy */}
        <div className="cr-ch" style={{ gridColumn: 'span 2' }}><div className="num">CH8</div><h3>Knowledge Entropy <span>· lower = more understood</span></h3>
          <div className="cr-ent">
            {(data.entropy?.byProject || []).map((p) => {
              const h = Math.round(p.entropy * 100);
              const c = p.entropy > 0.6 ? '#ff5470' : p.entropy > 0.4 ? '#ffb454' : '#39d98a';
              return (
                <div className="cr-col" key={p.project}>
                  <div className="box"><i style={{ height: h + '%', background: c }} /></div>
                  <span>{p.project.length > 8 ? p.project.slice(0, 7) + '…' : p.project}<br />{p.entropy}</span>
                </div>
              );
            })}
          </div>
          <div className="cr-tag">overall {data.entropy?.overall} — the goal is to make this bar fall</div>
        </div>
      </div>

      <div className="cr-foot">
        <span>VALIDATION BOARD —</span>
        <span>reproducibility <b>{v.reproducibility}</b></span>·
        <span>discrimination <b>{v.discrimination ? '✓' : '✗'}</b></span>·
        <span>independence <b>{v.independence ? '✓' : '✗'}</b></span>·
        <span>sensitivity <b>{v.sensitivity}</b></span>·
        <span>authority isolation <b>{v.authorityIsolation}</b></span>·
        <span>reasoning <b>{v.reasoning}</b></span>·
        <span>promotable <b>{v.promotable ? 'YES' : 'no'}</b> · auto-promote <b style={{ color: '#ff9f43' }}>{v.autoPromote ? 'yes' : 'no — a human decides'}</b></span>
      </div>

      <div className="cr-legend">LEARNING light: dark = no change · lit = evidence in · blinking = knowledge event · violet = discovery · amber = boundary · red = refutation. &nbsp; Read-only view — sources/feed are SAMPLE until SharePoint opens.</div>
    </div>
  );
}
